import { addIcons } from 'ionicons';
import { 
  timeOutline, 
  notificationsOutline, 
  trophyOutline,
  personOutline,
  watchOutline,
  checkmarkCircleOutline,
  addCircleOutline,
  moonOutline,
  footstepsOutline,
  heartOutline,
  pulseOutline,
  logOutOutline,
  leafOutline,
  iceCreamOutline,
  bookOutline,
  homeOutline,
  home,
  leaf,
  calendarOutline,
  calendar,
  person,
  addOutline,
  add,
  notifications,
  trophy,
  moon,
  waterOutline,
  water,
  footsteps,
  bookmarkOutline,
  bookmark,
  iceCream,
  cafeOutline,
  cafe,
  fitnessOutline,
  fitness,
  book,
  checkmark,
  chevronForward,
  checkmarkCircle,
  time,
  nutritionOutline,
  heart,
  flowerOutline,
  giftOutline,
  fastFoodOutline,
  fastFood
} from 'ionicons/icons';

// Реєструємо всі іконки один раз
addIcons({
  // Outline іконки
  'time-outline': timeOutline,
  'notifications-outline': notificationsOutline,
  'trophy-outline': trophyOutline,
  'person-outline': personOutline,
  'watch-outline': watchOutline,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'add-circle-outline': addCircleOutline,
  'moon-outline': moonOutline,
  'footsteps-outline': footstepsOutline,
  'heart-outline': heartOutline,
  'pulse-outline': pulseOutline,
  'log-out-outline': logOutOutline,
  'leaf-outline': leafOutline,
  'ice-cream-outline': iceCreamOutline,
  'book-outline': bookOutline,
  'home-outline': homeOutline,
  'calendar-outline': calendarOutline,
  'add-outline': addOutline,
  'water-outline': waterOutline,
  'bookmark-outline': bookmarkOutline,
  'cafe-outline': cafeOutline,
  'fitness-outline': fitnessOutline,
  'flower-outline': flowerOutline,
  'gift-outline': giftOutline,
  'fast-food-outline': fastFoodOutline,

  // Filled іконки
  'home': home,
  'leaf': leaf,
  'calendar': calendar,
  'person': person,
  'add': add,
  'notifications': notifications,
  'trophy': trophy,
  'moon': moon,
  'water': water,
  'footsteps': footsteps,
  'bookmark': bookmark,
  'ice-cream': iceCream,
  'cafe': cafe,
  'fitness': fitness,
  'book': book,
  'checkmark': checkmark,
  'chevron-forward': chevronForward,
  'checkmark-circle': checkmarkCircle,
  'time': time,
  'heart': heart,
  'cookies': fastFood,
  'fast-food': fastFood
}); 